package services;

import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import java.io.File;
import java.io.IOException;
import java.util.Properties;

public class MailSender {
    private static final String SENDER_EMAIL = "admissionscommittee57@gmail.com";

    //application password generated by gmail
    private static final String PASSWORD = "qukpmuxvczwqebic";
    private static final String HOST = "smtp.gmail.com";
    private static final int PORT = 465;

    public void sendGmail(String recipientEmail, String facultyName) {
        Properties props = new Properties();
        props.put("mail.smtp.user", SENDER_EMAIL);
        props.put("mail.smtp.host", HOST);
        props.put("mail.smtp.port", PORT);
        props.put("mail.smtp.starttls.enable","true");
        props.put("mail.smtp.debug", "true");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.socketFactory.port", PORT);
        props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.socketFactory.fallback", "false");

        Session session = Session.getInstance(props, null);
        session.setDebug(true);

        try {
            MimeMessage message = new MimeMessage(session);
            message.setFrom(new InternetAddress(SENDER_EMAIL));
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(recipientEmail));
            message.setSubject("Рішення приймальної комісії");

            Multipart multipart = new MimeMultipart();
            if(facultyName != null){
                MimeBodyPart textPart = new MimeBodyPart();
                textPart.setText("Вітаємо! Ви прийняті приймальною комісією на факультет " + facultyName +
                        ". Ви можете переглянути відомість у вкладеному файлі");
                multipart.addBodyPart(textPart);

                MimeBodyPart attachmentPart = new MimeBodyPart();
                File register = new File("D:/My Final Project/Admissions_committee/src/main/webapp/register/" + facultyName + "Register.pdf");
                attachmentPart.attachFile(register);
                multipart.addBodyPart(attachmentPart);
            } else {
                MimeBodyPart textPart = new MimeBodyPart();
                textPart.setText("Доброго дня! Нажаль цього року приймальна комісія прийняла рішення " +
                        "не допустити Вас до навчального процесу у зв'язку із відсутністю документів");
                multipart.addBodyPart(textPart);
            }
            message.setContent(multipart);

            Transport transport = session.getTransport("smtps");
            transport.connect(HOST, PORT, SENDER_EMAIL, PASSWORD);
            transport.sendMessage(message, message.getAllRecipients());
            transport.close();

    } catch (MessagingException e) {
            throw new RuntimeException(e);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

    }}
